# -*- coding: utf-8 -*-
"""Untitled19.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yQWrVw5-kxYKoSLW-naMkV4w2OMqVp-y
"""

import streamlit as st
import pandas as pd
import pulp
import math
import random
import re
import io
from datetime import datetime, timedelta
import plotly.express as px
import plotly.graph_objects as go

# ============================================================
# 1. KONFIGURASI HALAMAN
# ============================================================
st.set_page_config(page_title="DSS Penjadwalan Job Shop", layout="wide", page_icon="🏭")

st.markdown("""
<style>
.main-header{font-size:2.2rem;font-weight:700;color:#1E3A8A;margin-bottom:0}
.sub-header{font-size:1.05rem;color:#64748B;margin-bottom:16px}
.badge-winner{background:#DCFCE7;color:#166534;padding:4px 12px;border-radius:20px;font-weight:600}
.badge-loser{background:#FEE2E2;color:#991B1B;padding:4px 12px;border-radius:20px;font-weight:600}
.info-box{background:#EFF6FF;border-left:4px solid #3B82F6;padding:10px 14px;border-radius:4px;
          font-size:0.9rem;color:#1E40AF;margin:8px 0}
.warn-box{background:#FFFBEB;border-left:4px solid #F59E0B;padding:10px 14px;border-radius:4px;
          font-size:0.9rem;color:#92400E;margin:8px 0}
</style>
""", unsafe_allow_html=True)

st.markdown('<p class="main-header">🏭 DSS: Optimasi Penjadwalan Produksi</p>', unsafe_allow_html=True)
st.markdown(
    '<p class="sub-header">Routing Dinamis (OPC) · Dual-Engine Optimizer (SA + MILP) · '
    'EDD Baseline · Estimasi Due Date Order Baru</p>',
    unsafe_allow_html=True,
)
st.divider()

# ============================================================
# 2. KONSTANTA GLOBAL
# ============================================================
STATIONS = [
    '1. Potong',
    '2. Jahit_KaosPolo',
    '3. Jahit_KemejaJaket',
    '4. Sablon',
    '5. DTF',
    '6. Bordir',
    '7. Pasang_Kancing',
    '8. Buang_Benang',
    '9. Lipat',
    '10. Packing',
]

REQUIRED_COLUMNS = [
    'id pesanan', 'jenis produk', 'qty', 'due date (tanggal)',
    'furing', 'sablon', 'dtf', 'bordir', 'pasang kancing',
]
BINARY_COLUMNS = ['furing', 'sablon', 'dtf', 'bordir', 'pasang kancing']

MENIT_PER_HARI  = 450   # 08:30–11:30 (180 mnt) + 13:00–17:30 (270 mnt)
MENIT_ISTIRAHAT = 90    # durasi jeda siang dalam kalender (11:30–13:00)


# ============================================================
# 3. LOAD & VALIDASI DATA
# ============================================================
def load_order_file(uploaded_file):
    fn = uploaded_file.name.lower()
    if fn.endswith('.csv'):
        df = pd.read_csv(uploaded_file)
    elif fn.endswith(('.xlsx', '.xls')):
        df = pd.read_excel(uploaded_file)
    else:
        raise ValueError("Format tidak didukung. Gunakan CSV atau Excel (.xlsx/.xls).")

    df.columns = df.columns.str.lower().str.strip()
    missing = [c for c in REQUIRED_COLUMNS if c not in df.columns]
    if missing:
        raise ValueError(f"Kolom wajib tidak ditemukan: {missing}")

    df = df[REQUIRED_COLUMNS].copy()
    df['id pesanan']   = df['id pesanan'].astype(str).str.strip()
    df['jenis produk'] = df['jenis produk'].astype(str).str.strip().str.lower()

    mapping = {'kaos': 'kaos', 'polo': 'polo', 'kemeja': 'kemeja', 'jaket': 'jaket'}
    df['jenis produk'] = df['jenis produk'].replace(mapping)
    unknown = sorted(set(df['jenis produk']) - set(mapping))
    if unknown:
        raise ValueError(f"Jenis produk tidak dikenali: {unknown}")

    df['qty'] = pd.to_numeric(df['qty'], errors='coerce')
    for col in BINARY_COLUMNS:
        df[col] = pd.to_numeric(df[col], errors='coerce')
    df['due date (tanggal)'] = pd.to_datetime(
        df['due date (tanggal)'], errors='coerce', dayfirst=True
    )

    null_mask = df[['qty', 'due date (tanggal)'] + BINARY_COLUMNS].isnull().any(axis=1)
    if null_mask.any():
        raise ValueError(
            f"Data kosong/invalid di baris: {df.index[null_mask].tolist()}. "
            "Cek kolom qty, due date, dan flag 0/1."
        )
    if (df['qty'] <= 0).any():
        raise ValueError(f"qty <= 0 pada order: {df.loc[df['qty']<=0,'id pesanan'].tolist()}")
    for col in BINARY_COLUMNS:
        inv = df.loc[~df[col].isin([0, 1]), col].unique().tolist()
        if inv:
            raise ValueError(f"Kolom '{col}' hanya boleh 0 atau 1. Nilai: {inv}")

    return df


# ============================================================
# 4. WAKTU PROSES (OPC / ROUTING DINAMIS)
# [ASUMSI DIDEKLARASIKAN]: Model menggunakan representasi parallel machine agregat.
# Pᵢₘ = Qty / (kapasitas_satuan_mnt × jumlah_mesin_paralel)
# Contoh: 100 kemeja × (1/0.03 mnt/pcs) ÷ 3 tim jahit = 1111 mnt
# Ini merepresentasikan waktu yang diperlukan jika seluruh mesin paralel
# di stasiun m bekerja secara bersamaan untuk menyelesaikan pesanan i.
# ============================================================
def hitung_waktu_proses(row, resources, setup_time):
    qty   = row['qty']
    jenis = str(row['jenis produk']).lower()
    furing = row['furing']
    P = {m: 0.0 for m in STATIONS}

    # 1. Potong — kapasitas per operator × jumlah operator
    cap_potong = 1000
    if jenis in ('kemeja', 'jaket'):
        cap_potong = 125 if furing == 1 else 250
    # cap_potong dalam satuan pcs/hari; P dalam menit
    P['1. Potong'] = (qty / (cap_potong * resources['1. Potong'])) * MENIT_PER_HARI

    # 2/3. Jahit — dua jalur eksklusif (Kaos/Polo vs Kemeja/Jaket)
    if jenis in ('kaos', 'polo'):
        cap_j = 112.5 if jenis == 'kaos' else 55
        P['2. Jahit_KaosPolo'] = (qty / (cap_j * resources['2. Jahit_KaosPolo'])) * MENIT_PER_HARI
    elif jenis in ('kemeja', 'jaket'):
        base = 13.5 if jenis == 'kemeja' else 11.0
        if furing == 1:
            base *= 2 / 3
        P['3. Jahit_KemejaJaket'] = (qty / (base * resources['3. Jahit_KemejaJaket'])) * MENIT_PER_HARI

    # Dekorasi (opsional, dikontrol flag biner)
    if row['sablon'] == 1:
        P['4. Sablon'] = (qty / (700   * resources['4. Sablon']))   * MENIT_PER_HARI
    if row['dtf']    == 1:
        P['5. DTF']    = (qty / (750   * resources['5. DTF']))      * MENIT_PER_HARI
    if row['bordir'] == 1:
        P['6. Bordir'] = (qty / (442.5 * resources['6. Bordir']))   * MENIT_PER_HARI

    # Pasang kancing (bukan kaos)
    if row['pasang kancing'] == 1 and jenis != 'kaos':
        cap_k = 400 if jenis == 'polo' else 125
        P['7. Pasang_Kancing'] = (qty / (cap_k * resources['7. Pasang_Kancing'])) * MENIT_PER_HARI

    # Finishing — selalu ada
    cap_benang = 166.67 if furing == 1 else 500
    P['8. Buang_Benang'] = (qty / (cap_benang * resources['8. Buang_Benang'])) * MENIT_PER_HARI
    P['9. Lipat']        = (qty / (500 * resources['9. Lipat']))                * MENIT_PER_HARI
    P['10. Packing']     = (qty / (500 * resources['10. Packing']))             * MENIT_PER_HARI

    # Setup time pada setiap stasiun aktif
    for m in STATIONS:
        if P[m] > 0:
            P[m] += setup_time

    return P


# ============================================================
# 5. KONVERSI WAKTU: MENIT EFEKTIF ↔ JAM DINDING
# ============================================================
def konversi_ke_jam_dinding(menit_efektif, start_date):
    """Konversi menit efektif (linear, skip Minggu & istirahat) ke datetime nyata."""
    hari_ke = int(menit_efektif // MENIT_PER_HARI)
    sisa    = menit_efektif % MENIT_PER_HARI

    current       = start_date
    hari_ditambah = 0
    while hari_ditambah < hari_ke:
        current += timedelta(days=1)
        if current.weekday() != 6:
            hari_ditambah += 1

    if current.weekday() == 6:
        current += timedelta(days=1)

    base = current.replace(hour=8, minute=30, second=0, microsecond=0)
    if sisa <= 180:
        return base + timedelta(minutes=sisa)
    else:
        return base + timedelta(minutes=sisa + MENIT_ISTIRAHAT)


def hitung_target_menit(target_dt, start_dt):
    """Menit efektif dari start_dt sampai target_dt (17:30 hari due date)."""
    if target_dt <= start_dt:
        return 0

    total   = 0
    current = start_dt

    while current.date() < target_dt.date():
        if current.weekday() != 6:
            total += MENIT_PER_HARI
        current += timedelta(days=1)

    if target_dt.weekday() != 6:
        jam_mulai_hari = current.replace(hour=8, minute=30, second=0, microsecond=0)
        delta_kal      = (target_dt - jam_mulai_hari).total_seconds() / 60
        if delta_kal <= 0:
            mnt_hari_ini = 0
        elif delta_kal <= 180:
            mnt_hari_ini = delta_kal
        elif delta_kal <= 180 + MENIT_ISTIRAHAT:
            mnt_hari_ini = 180
        else:
            mnt_hari_ini = delta_kal - MENIT_ISTIRAHAT
        total += mnt_hari_ini

    return total


def pecah_balok_gantt(start_efektif, durasi, start_date):
    """Pecah blok tugas agar tidak menembus batas sesi/hari untuk rendering Gantt."""
    blocks      = []
    tersisa     = durasi
    cur_efektif = start_efektif

    while tersisa > 0.01:
        mnt_di_hari = cur_efektif % MENIT_PER_HARI
        if mnt_di_hari < 180:
            chunk = min(tersisa, 180 - mnt_di_hari)
        else:
            chunk = min(tersisa, MENIT_PER_HARI - mnt_di_hari)

        if chunk < 0.01:
            cur_efektif += 0.01
            continue

        blocks.append({
            'start_nyata'    : konversi_ke_jam_dinding(cur_efektif, start_date),
            'end_nyata'      : konversi_ke_jam_dinding(cur_efektif + chunk, start_date),
            'durasi_potongan': chunk,
        })
        cur_efektif += chunk
        tersisa     -= chunk

    return blocks


# ============================================================
# 6. SIMULATED ANNEALING
# Release date diimplementasikan: start = max(m_avail, j_avail, R[j])
# ============================================================
def run_simulated_annealing(jobs, P_dict, D_dict, W_dict, R_dict,
                             locked_jobs=None, locked_schedule=None):
    """
    SA untuk Weighted Total Tardiness Minimization pada Job Shop.
    - jobs          : list semua job ID yang akan dijadwalkan
    - R_dict        : release date per job (menit efektif)
    - locked_jobs   : set job ID yang posisinya dikunci (tidak ikut permutasi)
    - locked_schedule: dict {job_id: {stasiun: start_time}} untuk job terkunci
    """
    if locked_jobs is None:
        locked_jobs = set()
    if locked_schedule is None:
        locked_schedule = {}

    free_jobs   = [j for j in jobs if j not in locked_jobs]
    locked_list = [j for j in jobs if j in locked_jobs]

    def eval_seq(free_seq):
        """Evaluasi sekuens: locked jobs diinjeksikan ke jadwal berdasarkan posisi fixednya."""
        m_avail = {m: 0.0 for m in STATIONS}
        j_avail = {}

        # Inisialisasi locked jobs ke m_avail berdasarkan jadwal existing
        for lj in locked_list:
            lj_end = 0
            for m in STATIONS:
                if lj in locked_schedule and m in locked_schedule[lj]:
                    s  = locked_schedule[lj][m]
                    dur = P_dict[lj][m]
                    e   = s + dur
                    # Blokir mesin sampai locked job selesai
                    m_avail[m] = max(m_avail[m], e)
                    lj_end = max(lj_end, e)
            j_avail[lj] = lj_end

        total_tard = 0
        sched      = []

        # Tambahkan tugas locked ke sched untuk visualisasi
        for lj in locked_list:
            if lj in locked_schedule:
                for m, s in locked_schedule[lj].items():
                    dur = P_dict[lj].get(m, 0)
                    if dur > 0:
                        sched.append({'job': lj, 'm': m, 'start': s, 'dur': dur})
            tard_lj = max(0, j_avail.get(lj, 0) - D_dict[lj]) * W_dict[lj]
            total_tard += tard_lj

        # Jadwalkan free jobs dalam urutan free_seq
        for j in free_seq:
            rute       = [m for m in STATIONS if P_dict[j][m] > 0]
            j_avail[j] = R_dict[j]   # [FIX-1] release date constraint
            for m in rute:
                dur   = P_dict[j][m]
                start = max(m_avail[m], j_avail[j])
                end   = start + dur
                m_avail[m] = end
                j_avail[j] = end
                sched.append({'job': j, 'm': m, 'start': start, 'dur': dur})
            total_tard += max(0, j_avail[j] - D_dict[j]) * W_dict[j]

        return total_tard, sched, j_avail

    def swap(seq):
        s = seq.copy()
        if len(s) < 2:
            return s
        a, b = random.sample(range(len(s)), 2)
        s[a], s[b] = s[b], s[a]
        return s

    def insert(seq):
        s = seq.copy()
        if len(s) < 2:
            return s
        a   = random.randrange(len(s))
        job = s.pop(a)
        b   = random.randrange(len(s) + 1)
        s.insert(b, job)
        return s

    # Inisialisasi dengan EDD
    cur_seq    = sorted(free_jobs, key=lambda x: D_dict[x])
    cur_score, _, _ = eval_seq(cur_seq)
    best_seq   = cur_seq.copy()
    best_score = cur_score

    T_sa    = 500.0
    cooling = 0.997
    n_iter  = 8000

    for _ in range(n_iter):
        new_seq   = swap(cur_seq) if random.random() < 0.7 else insert(cur_seq)
        new_score, _, _ = eval_seq(new_seq)
        delta     = new_score - cur_score

        if delta < 0 or (T_sa > 1e-10 and random.random() < math.exp(-delta / T_sa)):
            cur_seq   = new_seq
            cur_score = new_score
            if new_score < best_score:
                best_seq   = new_seq.copy()
                best_score = new_score

        T_sa *= cooling

    _, final_sched, final_end = eval_seq(best_seq)
    return best_score, final_sched, final_end


# ============================================================
# 7. EDD BASELINE (Earliest Due Date — dispatching rule murni)
# [FIX-3] Tambahan baseline ketiga untuk perbandingan
# ============================================================
def run_edd_baseline(jobs, P_dict, D_dict, W_dict, R_dict):
    """
    Evaluasi jadwal EDD murni (tanpa iterasi optimasi).
    Urutan: diurutkan ascending berdasarkan due date, tidak diubah.
    """
    edd_seq    = sorted(jobs, key=lambda x: D_dict[x])
    m_avail    = {m: 0.0 for m in STATIONS}
    j_avail    = {j: R_dict[j] for j in jobs}   # [FIX-1] release date
    total_tard = 0
    sched      = []

    for j in edd_seq:
        rute = [m for m in STATIONS if P_dict[j][m] > 0]
        for m in rute:
            dur   = P_dict[j][m]
            start = max(m_avail[m], j_avail[j])
            end   = start + dur
            m_avail[m] = end
            j_avail[j] = end
            sched.append({'job': j, 'm': m, 'start': start, 'dur': dur})
        total_tard += max(0, j_avail[j] - D_dict[j]) * W_dict[j]

    return total_tard, sched, j_avail


# ============================================================
# 8. HELPER UTILITIES
# ============================================================
def safe_var_name(s):
    """Hilangkan karakter non-alphanumeric dari nama variabel PuLP."""
    return re.sub(r'[^A-Za-z0-9_]', '_', str(s))


def build_gantt_df(sched_list, df_pool, start_date):
    rows = []
    for t in sched_list:
        match = df_pool[df_pool['id pesanan'].astype(str) == t['job']]
        qty_val = match['qty'].iloc[0] if not match.empty else 0
        for blk in pecah_balok_gantt(t['start'], t['dur'], start_date):
            rows.append({
                'Stasiun Kerja' : t['m'],
                'ID Pesanan'    : t['job'],
                'Qty'           : qty_val,
                'Mulai'         : blk['start_nyata'],
                'Selesai'       : blk['end_nyata'],
                'Durasi (Menit)': round(blk['durasi_potongan'], 2),
            })
    return pd.DataFrame(rows)


# ============================================================
# 9. SANITY CHECK
# ============================================================
def jalankan_sanity_check(jadwal_final, df_pool, P_dict, start_date):
    log            = []
    err_overlap    = False
    err_presedens  = False

    log.append("=" * 60)
    log.append("🔍 SANITY CHECK — VERIFIKASI LOGIKA JADWAL")
    log.append("=" * 60)

    # [1] Overlap mesin
    log.append("\n[1/3] Memeriksa Overlap Kapasitas Mesin...")
    for st_name in STATIONS:
        tasks = sorted([t for t in jadwal_final if t['m'] == st_name], key=lambda x: x['start'])
        for i in range(1, len(tasks)):
            prev, curr = tasks[i-1], tasks[i]
            gap = curr['start'] - (prev['start'] + prev['dur'])
            if gap < -0.01:
                log.append(
                    f"  ❌ OVERLAP di {st_name}: Order {prev['job']} & {curr['job']} "
                    f"bentrok! (gap={gap:.2f} mnt)"
                )
                err_overlap = True
    if not err_overlap:
        log.append("  ✔️ LULUS: Tidak ada tumpang tindih antar order di setiap stasiun.")

    # [2] Presedensi
    log.append("\n[2/3] Memeriksa Presedensi (Urutan Stasiun per Pesanan)...")
    for job in set(t['job'] for t in jadwal_final):
        tasks_j = sorted([t for t in jadwal_final if t['job'] == job], key=lambda x: x['start'])
        for i in range(1, len(tasks_j)):
            prev, curr = tasks_j[i-1], tasks_j[i]
            gap = curr['start'] - (prev['start'] + prev['dur'])
            if gap < -0.01:
                log.append(
                    f"  ❌ ERROR Order {job}: {curr['m']} mulai sebelum {prev['m']} selesai!"
                )
                err_presedens = True
    if not err_presedens:
        log.append("  ✔️ LULUS: Semua urutan stasiun per pesanan sudah benar.")

    # [3] Hari Minggu
    log.append("\n[3/3] Memeriksa Jadwal di Hari Minggu...")
    minggu_rows = []
    for t in jadwal_final:
        for blk in pecah_balok_gantt(t['start'], t['dur'], start_date):
            if blk['start_nyata'].weekday() == 6:
                minggu_rows.append({
                    'ID Pesanan': t['job'],
                    'Stasiun'   : t['m'],
                    'Mulai'     : blk['start_nyata'].strftime('%d-%b-%y %H:%M'),
                    'Selesai'   : blk['end_nyata'].strftime('%d-%b-%y %H:%M'),
                })
    if minggu_rows:
        log.append(f"  ❌ DITEMUKAN {len(minggu_rows)} tugas dijadwalkan di Hari Minggu!")
    else:
        log.append("  ✔️ LULUS: Tidak ada jadwal aktif di Hari Minggu.")

    log.append("\n" + "=" * 60)
    if err_overlap or err_presedens or minggu_rows:
        log.append("🚨 SANITY CHECK GAGAL! Ada pelanggaran yang perlu diperiksa.")
    else:
        log.append("✅ SANITY CHECK PASSED! Jadwal valid — tidak ada pelanggaran.")
    log.append("=" * 60)

    all_jobs      = list(set(t['job'] for t in jadwal_final))
    sample_job_id = random.choice(all_jobs)
    sample_row_df = df_pool[df_pool['id pesanan'].astype(str) == sample_job_id]
    sample_row    = sample_row_df.iloc[0].to_dict() if not sample_row_df.empty else {}
    sample_sched  = sorted(
        [t for t in jadwal_final if t['job'] == sample_job_id], key=lambda x: x['start']
    )
    sample_rute   = [t['m'] for t in sample_sched]

    return {
        'log_text'      : "\n".join(log),
        'err_overlap'   : err_overlap,
        'err_presedens' : err_presedens,
        'sample_job_id' : sample_job_id,
        'sample_row'    : sample_row,
        'sample_sched'  : sample_sched,
        'sample_rute'   : sample_rute,
        'tabel_minggu'  : pd.DataFrame(minggu_rows) if minggu_rows else pd.DataFrame(),
    }


# ============================================================
# 10. INSERTION ESTIMATOR — Fitur Baru
# Joint re-optimization: locked jobs dipertahankan posisinya,
# free jobs + new jobs di-reschedule ulang bersama.
# ============================================================
def estimasi_order_baru(
    new_jobs_data,      # list of dict: data order baru (sama format dengan jobs_raw)
    existing_job_ids,   # list semua job ID di jadwal existing
    locked_job_ids,     # set job ID yang dikunci
    existing_schedule,  # dict {job_id: {stasiun: start_time}} dari jadwal winning
    P_dict_existing,    # dict Pᵢₘ untuk existing jobs
    D_dict_existing,    # dict due date untuk existing jobs
    W_dict_existing,    # dict bobot untuk existing jobs
    R_dict_existing,    # dict release date untuk existing jobs
    resources,
    setup_time,
    start_date,
    priority_weight,
    milp_time_limit,
):
    """
    Estimasi earliest completion time untuk order baru sambil menjaga
    order yang terkunci tidak terlambat.

    Pendekatan: Joint re-optimization (Pendekatan B)
    - Locked jobs: posisi dipertahankan dengan hard constraint di MILP
    - Free (unlocked) jobs + new jobs: di-reschedule ulang bersama
    - Jaminan: locked jobs TIDAK bisa terlambat (constraint ketat)
    """
    # Hitung Pᵢₘ untuk order baru
    new_job_ids = []
    P_new       = {}
    D_new       = {}
    W_new       = {}
    R_new       = {}

    for nj in new_jobs_data:
        jid       = str(nj['id pesanan'])
        new_job_ids.append(jid)
        P_new[jid] = hitung_waktu_proses(nj, resources, setup_time)

        # Due date order baru: gunakan tanggal yang diberikan user
        target_dt   = nj['due date (tanggal)'].replace(hour=17, minute=30, second=0, microsecond=0)
        D_new[jid]  = hitung_target_menit(target_dt, start_date)
        W_new[jid]  = priority_weight if nj.get('Priority', False) else 1
        # Release date order baru = saat estimasi dilakukan = start dari horizon
        R_new[jid]  = hitung_target_menit(
            nj.get('release_dt', start_date).replace(hour=8, minute=30, second=0, microsecond=0),
            start_date
        ) if 'release_dt' in nj else 0

    # Gabungkan semua job
    all_ids   = existing_job_ids + new_job_ids
    P_all     = {**P_dict_existing, **P_new}
    D_all     = {**D_dict_existing, **D_new}
    W_all     = {**W_dict_existing, **W_new}
    R_all     = {**R_dict_existing, **R_new}

    locked_sched_map = {}
    for lj in locked_job_ids:
        if lj in existing_schedule:
            locked_sched_map[lj] = existing_schedule[lj]

    # ── SA untuk warm start ──────────────────────────────────
    sa_score, sa_sched, sa_end = run_simulated_annealing(
        all_ids, P_all, D_all, W_all, R_all,
        locked_jobs=locked_job_ids,
        locked_schedule=locked_sched_map,
    )

    # ── MILP dengan hard constraint untuk locked jobs ────────
    milp_score    = float('inf')
    milp_feasible = False
    milp_sched    = []
    milp_end      = {}
    gap_pct       = None

    if len(all_ids) >= 2:
        prob     = pulp.LpProblem("Insertion_JobShop", pulp.LpMinimize)
        S        = pulp.LpVariable.dicts("S",    (all_ids, STATIONS), lowBound=0, cat='Continuous')
        Tard_var = pulp.LpVariable.dicts("Tard", all_ids,             lowBound=0, cat='Continuous')

        # BigM per-mesin (ketat)
        BigM_per_mesin = {}
        for m in STATIONS:
            total_dur = sum(P_all[i][m] for i in all_ids if P_all[i][m] > 0)
            BigM_per_mesin[m] = max(total_dur, 1.0)

        # Variabel biner hanya untuk pasangan yang share mesin
        Y = {}
        for m in STATIONS:
            aktif = [i for i in all_ids if P_all[i][m] > 0]
            for a in range(len(aktif)):
                for b in range(a + 1, len(aktif)):
                    i, j = aktif[a], aktif[b]
                    vname = f"Y_{safe_var_name(i)}_{safe_var_name(j)}_{safe_var_name(m)}"
                    Y[(i, j, m)] = pulp.LpVariable(vname, cat='Binary')

        # Objektif: minimize weighted tardiness semua job
        prob += pulp.lpSum(W_all[i] * Tard_var[i] for i in all_ids)

        for i in all_ids:
            rute = [m for m in STATIONS if P_all[i][m] > 0]

            # [FIX-1] Release date constraint
            if rute:
                prob += S[i][rute[0]] >= R_all[i]

            # Presedensi
            for k in range(1, len(rute)):
                prob += S[i][rute[k]] >= S[i][rute[k-1]] + P_all[i][rute[k-1]]

            # Tardiness
            if rute:
                prob += Tard_var[i] >= (S[i][rute[-1]] + P_all[i][rute[-1]]) - D_all[i]

            # [KEY] Hard constraint: locked jobs — posisi tidak bergerak
            if i in locked_job_ids and i in locked_sched_map:
                for m, fixed_start in locked_sched_map[i].items():
                    if P_all[i].get(m, 0) > 0:
                        prob += S[i][m] == fixed_start
                # Tambahan: locked job harus TEPAT WAKTU (Tardiness = 0)
                prob += Tard_var[i] == 0

        # No-overlap per mesin
        for (i, j, m), y_var in Y.items():
            bm = BigM_per_mesin[m]
            prob += S[j][m] >= S[i][m] + P_all[i][m] - bm * y_var
            prob += S[i][m] >= S[j][m] + P_all[j][m] - bm * (1 - y_var)

        # Warm-start dari SA
        sa_start_map = {(e['job'], e['m']): e['start'] for e in sa_sched}
        for i in all_ids:
            for m in STATIONS:
                val = sa_start_map.get((i, m))
                if val is not None:
                    try:
                        S[i][m].setInitialValue(val)
                    except Exception:
                        pass
        for (i, j, m), y_var in Y.items():
            si = sa_start_map.get((i, m))
            sj = sa_start_map.get((j, m))
            if si is not None and sj is not None:
                try:
                    y_var.setInitialValue(1 if sj < si else 0)
                except Exception:
                    pass

        prob.solve(pulp.PULP_CBC_CMD(timeLimit=milp_time_limit, msg=0, warmStart=True))

        milp_status   = pulp.LpStatus[prob.status]
        obj_val       = pulp.value(prob.objective)
        milp_feasible = milp_status in ('Optimal', 'Feasible') and obj_val is not None
        milp_score    = float(obj_val) if milp_feasible else float('inf')

        # [FIX-2] Optimality gap
        if milp_feasible:
            best_bound = getattr(prob, 'bestBound', None)
            if best_bound is not None and milp_score > 0:
                gap_pct = abs(milp_score - float(best_bound)) / (abs(milp_score) + 1e-10) * 100
            else:
                gap_pct = 0.0 if milp_status == 'Optimal' else None

            for i in all_ids:
                rute = [m for m in STATIONS if P_all[i][m] > 0]
                if rute:
                    milp_end[i] = (S[i][rute[-1]].varValue or 0) + P_all[i][rute[-1]]
                else:
                    milp_end[i] = 0
                for m in rute:
                    milp_sched.append({
                        'job'  : i,
                        'm'    : m,
                        'start': round(S[i][m].varValue or 0, 2),
                        'dur'  : P_all[i][m],
                    })

    # Pilih solusi terbaik
    if milp_feasible and milp_score <= sa_score:
        final_sched = milp_sched
        final_end   = milp_end
        method_used = f"MILP (gap: {gap_pct:.2f}%)" if gap_pct is not None else "MILP"
        final_score = milp_score
    else:
        final_sched = sa_sched
        final_end   = sa_end
        method_used = "Simulated Annealing"
        final_score = sa_score

    return {
        'sched'        : final_sched,
        'end_times'    : final_end,
        'method'       : method_used,
        'score'        : final_score,
        'gap_pct'      : gap_pct,
        'new_job_ids'  : new_job_ids,
        'P_new'        : P_new,
        'D_new'        : D_new,
    }


# ============================================================
# 11. SIDEBAR
# ============================================================
with st.sidebar:
    st.image("https://cdn-icons-png.flaticon.com/512/2043/2043236.png", width=60)
    st.header("⚙️ Konfigurasi Sistem")

    # Asumsi model — dideklarasikan eksplisit [FIX-1, FIX-7]
    with st.expander("ℹ️ Asumsi Model", expanded=False):
        st.markdown("""
**Release Date:** Semua order dalam dataset dianggap tersedia sejak *Tanggal Mulai Produksi*
(release date = start_date). Order baru yang diestimasi tersedia sejak tanggal input estimasi.

**Parallel Machine (Agregat):** Setiap stasiun dimodelkan sebagai satu entitas dengan kapasitas
agregat = `kapasitas_satuan × jumlah_mesin_paralel`. Artinya Pᵢₘ merepresentasikan total waktu
jika seluruh mesin paralel di stasiun m bekerja bersamaan untuk pesanan i.

**Non-Preemption:** Operasi yang sudah dimulai tidak dapat diinterupsi. Dijamin secara implisit
oleh struktur Big-M disjunctive constraint.
        """)

    with st.expander("📥 Template Data"):
        tpl = pd.DataFrame({
            'id pesanan'        : ['ORD-01', 'ORD-02'],
            'jenis produk'      : ['Kaos', 'Kemeja'],
            'qty'               : [100, 50],
            'due date (tanggal)': ['15/05/2026', '20/05/2026'],
            'furing'            : [0, 1],
            'sablon'            : [1, 0],
            'dtf'               : [0, 0],
            'bordir'            : [0, 1],
            'pasang kancing'    : [0, 1],
        })
        st.download_button(
            "⬇️ Download Template.csv",
            tpl.to_csv(index=False).encode('utf-8'),
            "Template_Order_Pabrik.csv", "text/csv",
        )

    uploaded_file    = st.file_uploader("1. Upload Data Order", type=['csv', 'xlsx', 'xls'])
    start_date_input = st.date_input("2. Tanggal Mulai Produksi", datetime.today())
    start_date       = datetime.combine(start_date_input, datetime.min.time()).replace(
        hour=8, minute=30
    )

    st.subheader("🛠️ Parameter Optimasi")

    # [FIX-4] Bobot prioritas menjadi parameter user
    priority_weight = st.number_input(
        "Bobot Pesanan Prioritas (W)",
        min_value=10, max_value=100_000, value=10_000, step=1_000,
        help=(
            "Keterlambatan 1 menit pesanan prioritas = W × keterlambatan pesanan normal. "
            "Nilai lebih tinggi = semakin agresif menjaga pesanan priority tepat waktu."
        ),
    )

    use_custom = st.checkbox("Ubah Kapasitas/Resource Default",
                             help="Simulasikan operator sakit atau mesin rusak.")

    res = {m: 1 for m in STATIONS}
    res['3. Jahit_KemejaJaket'] = 3
    res['8. Buang_Benang']      = 2
    setup_time_val = 0.0

    if use_custom:
        with st.container(border=True):
            setup_time_val              = st.number_input("Setup Antar Order (menit)", 0.0, 60.0, 0.0, 5.0)
            res['1. Potong']            = st.number_input("Operator Potong",           1, 10, 1)
            res['2. Jahit_KaosPolo']    = st.number_input("Tim Jahit Kaos/Polo",       1, 10, 1)
            res['3. Jahit_KemejaJaket'] = st.number_input("Tim Jahit Kemeja/Jaket",    1, 10, 3)
            res['4. Sablon']            = st.number_input("Mesin Sablon",              1, 10, 1)
            res['5. DTF']               = st.number_input("Mesin DTF",                 1, 10, 1)
            res['6. Bordir']            = st.number_input("Mesin Bordir",              1, 10, 1)
            res['7. Pasang_Kancing']    = st.number_input("Operator Pasang Kancing",   1, 10, 1)
            res['8. Buang_Benang']      = st.number_input("Operator Buang Benang",     1, 10, 2)
            res['9. Lipat']             = st.number_input("Operator Lipat",            1, 10, 1)
            res['10. Packing']          = st.number_input("Operator Packing",          1, 10, 1)

    milp_time_limit = st.slider(
        "⏱️ Batas Waktu MILP (detik)",
        min_value=60, max_value=600, value=300, step=30,
        help="Semakin lama, MILP semakin berpeluang menemukan solusi optimal.",
    )
    run_button = st.button("🚀 JALANKAN OPTIMASI", type="primary", use_container_width=True)


# ============================================================
# 12. MAIN AREA
# ============================================================
if uploaded_file is None:
    st.info("👈 Silakan unggah file CSV / Excel di panel kiri untuk memulai.")
else:
    try:
        df = load_order_file(uploaded_file)
        df['Bulan-Tahun'] = df['due date (tanggal)'].dt.strftime('%B %Y')

        with st.container(border=True):
            c1, c2 = st.columns(2)
            bulan_pilih = c1.selectbox("Filter Bulan Due Date:", ["Semua"] + list(df['Bulan-Tahun'].unique()))
            sortir      = c2.selectbox("Urutkan:", ["Due Date Terdekat", "Due Date Terjauh"])

        df_disp = df.copy() if bulan_pilih == "Semua" else df[df['Bulan-Tahun'] == bulan_pilih].copy()
        df_disp = df_disp.sort_values('due date (tanggal)', ascending=(sortir == "Due Date Terdekat"))

        for col, default in [("Pilih", False), ("Priority", False)]:
            if col not in df_disp.columns:
                df_disp.insert(0 if col == "Pilih" else 1, col, default)

        st.subheader("📋 Pemilihan & Prioritisasi Order")
        st.info(
            "💡 Centang **Pilih** untuk memasukkan order ke optimasi. "
            "Centang **Priority** untuk bobot penalti lebih tinggi (order VIP)."
        )

        edited_df = st.data_editor(
            df_disp.drop(columns=['Bulan-Tahun']),
            hide_index=True,
            use_container_width=True,
        )
        df_pool = edited_df[edited_df["Pilih"] == True].copy()

        # [FIX-6] Validasi due date sudah lewat
        if run_button or True:
            df_pool_temp = df_pool.copy()
            df_pool_temp['target_dt_check'] = df_pool_temp['due date (tanggal)'].apply(
                lambda x: x.replace(hour=17, minute=30, second=0, microsecond=0)
            )
            lewat = df_pool_temp[df_pool_temp['target_dt_check'] <= start_date]['id pesanan'].tolist()
            if lewat:
                st.warning(
                    f"⚠️ **{len(lewat)} pesanan sudah melewati due date** sebelum produksi dimulai "
                    f"dan akan otomatis terlambat: `{', '.join(str(x) for x in lewat)}`"
                )

        # ============================================================
        # 13. ENGINE OPTIMASI
        # ============================================================
        if run_button:
            if len(df_pool) == 0:
                st.warning("⚠️ Centang minimal 1 pesanan untuk dioptimasi.")
                st.stop()

            progress_bar = st.progress(0, text="Memulai optimasi…")

            # ── TAHAP 1: Preprocessing ─────────────────────────────────
            progress_bar.progress(5, "1/5 Kalkulasi routing & waktu proses…")

            df_pool = df_pool.copy()
            df_pool['target_dt'] = df_pool['due date (tanggal)'].apply(
                lambda x: x.replace(hour=17, minute=30, second=0, microsecond=0)
            )
            df_pool['target_menit'] = df_pool['target_dt'].apply(
                lambda x: hitung_target_menit(x, start_date)
            )

            jobs_raw = df_pool.to_dict('records')
            job_ids  = [str(j['id pesanan']) for j in jobs_raw]

            P = {str(j['id pesanan']): hitung_waktu_proses(j, res, setup_time_val) for j in jobs_raw}
            D = {str(j['id pesanan']): j['target_menit'] for j in jobs_raw}
            W = {str(j['id pesanan']): priority_weight if j['Priority'] else 1 for j in jobs_raw}
            # [FIX-1] Release date = 0 untuk semua (tersedia sejak start_date)
            R = {str(j['id pesanan']): 0 for j in jobs_raw}

            # ── TAHAP 2: EDD Baseline ──────────────────────────────────
            progress_bar.progress(15, "2/5 Menghitung EDD baseline…")
            edd_score, edd_sched, edd_end = run_edd_baseline(job_ids, P, D, W, R)

            # ── TAHAP 3: Simulated Annealing ───────────────────────────
            progress_bar.progress(25, "3/5 Simulated Annealing (8.000 iterasi)…")
            sa_score, sa_sched, sa_end = run_simulated_annealing(
                job_ids, P, D, W, R
            )

            # ── TAHAP 4: MILP ──────────────────────────────────────────
            progress_bar.progress(45, f"4/5 MILP/CBC (maks {milp_time_limit} detik)…")

            milp_score    = float('inf')
            milp_feasible = False
            milp_status   = "Not Run"
            milp_sched    = []
            milp_end      = {}
            bigm_info     = {}
            gap_pct_main  = None

            if len(job_ids) >= 2:
                prob     = pulp.LpProblem("JobShop_Garment_v5", pulp.LpMinimize)
                S        = pulp.LpVariable.dicts("S",    (job_ids, STATIONS), lowBound=0, cat='Continuous')
                Tard_var = pulp.LpVariable.dicts("Tard", job_ids,             lowBound=0, cat='Continuous')

                # BigM per-mesin
                BigM_per_mesin = {}
                for m in STATIONS:
                    total_dur = sum(P[i][m] for i in job_ids if P[i][m] > 0)
                    BigM_per_mesin[m] = max(total_dur, 1.0)
                    bigm_info[m]      = round(BigM_per_mesin[m], 1)

                # Variabel biner
                Y = {}
                for m in STATIONS:
                    aktif = [i for i in job_ids if P[i][m] > 0]
                    for a in range(len(aktif)):
                        for b in range(a + 1, len(aktif)):
                            i, j = aktif[a], aktif[b]
                            vname = f"Y_{safe_var_name(i)}_{safe_var_name(j)}_{safe_var_name(m)}"
                            Y[(i, j, m)] = pulp.LpVariable(vname, cat='Binary')

                # Objektif
                prob += pulp.lpSum(W[i] * Tard_var[i] for i in job_ids)

                for i in job_ids:
                    rute = [m for m in STATIONS if P[i][m] > 0]
                    # [FIX-1] Release date
                    if rute:
                        prob += S[i][rute[0]] >= R[i]
                    # Presedensi
                    for k in range(1, len(rute)):
                        prob += S[i][rute[k]] >= S[i][rute[k-1]] + P[i][rute[k-1]]
                    # Tardiness
                    if rute:
                        prob += Tard_var[i] >= (S[i][rute[-1]] + P[i][rute[-1]]) - D[i]

                # No-overlap
                for (i, j, m), y_var in Y.items():
                    bm = BigM_per_mesin[m]
                    prob += S[j][m] >= S[i][m] + P[i][m] - bm * y_var
                    prob += S[i][m] >= S[j][m] + P[j][m] - bm * (1 - y_var)

                # Warm-start dari SA
                sa_start_map = {(e['job'], e['m']): e['start'] for e in sa_sched}
                for i in job_ids:
                    for m in STATIONS:
                        val = sa_start_map.get((i, m))
                        if val is not None:
                            try:
                                S[i][m].setInitialValue(val)
                            except Exception:
                                pass
                for (i, j, m), y_var in Y.items():
                    si = sa_start_map.get((i, m))
                    sj = sa_start_map.get((j, m))
                    if si is not None and sj is not None:
                        try:
                            y_var.setInitialValue(1 if sj < si else 0)
                        except Exception:
                            pass

                prob.solve(pulp.PULP_CBC_CMD(
                    timeLimit=milp_time_limit, msg=0, warmStart=True
                ))

                milp_status   = pulp.LpStatus[prob.status]
                obj_val       = pulp.value(prob.objective)
                milp_feasible = milp_status in ('Optimal', 'Feasible') and obj_val is not None
                milp_score    = float(obj_val) if milp_feasible else float('inf')

                # [FIX-2] Optimality gap
                if milp_feasible:
                    best_bound = getattr(prob, 'bestBound', None)
                    if best_bound is not None and milp_score > 0:
                        gap_pct_main = abs(milp_score - float(best_bound)) / (abs(milp_score) + 1e-10) * 100
                    else:
                        gap_pct_main = 0.0 if milp_status == 'Optimal' else None

                    for i in job_ids:
                        rute = [m for m in STATIONS if P[i][m] > 0]
                        if rute:
                            milp_end[i] = (S[i][rute[-1]].varValue or 0) + P[i][rute[-1]]
                        else:
                            milp_end[i] = 0
                        for m in rute:
                            milp_sched.append({
                                'job'  : i,
                                'm'    : m,
                                'start': round(S[i][m].varValue or 0, 2),
                                'dur'  : P[i][m],
                            })

            # ── TAHAP 5: Showdown ──────────────────────────────────────
            progress_bar.progress(88, "5/5 Membandingkan & memfinalisasi…")

            scores = {
                'EDD'               : edd_score,
                'Simulated Annealing': sa_score,
                'MILP'              : milp_score,
            }
            scheds = {
                'EDD'               : edd_sched,
                'Simulated Annealing': sa_sched,
                'MILP'              : milp_sched if milp_feasible else [],
            }
            ends = {
                'EDD'               : edd_end,
                'Simulated Annealing': sa_end,
                'MILP'              : milp_end if milp_feasible else {},
            }

            pemenang = min(scores, key=scores.get)
            # Jika MILP tidak feasible, jangan pilih
            if pemenang == 'MILP' and not milp_feasible:
                pemenang = 'Simulated Annealing' if sa_score <= edd_score else 'EDD'

            jadwal_final       = scheds[pemenang]
            waktu_selesai_dict = ends[pemenang]
            score_pemenang     = scores[pemenang]

            # Simpan jadwal winning ke session state untuk fitur estimasi
            existing_schedule_map = {}
            for t in jadwal_final:
                if t['job'] not in existing_schedule_map:
                    existing_schedule_map[t['job']] = {}
                existing_schedule_map[t['job']][t['m']] = t['start']

            st.session_state['jadwal_final']       = jadwal_final
            st.session_state['existing_schedule']  = existing_schedule_map
            st.session_state['job_ids']            = job_ids
            st.session_state['P']                  = P
            st.session_state['D']                  = D
            st.session_state['W']                  = W
            st.session_state['R']                  = R
            st.session_state['df_pool']            = df_pool
            st.session_state['start_date']         = start_date
            st.session_state['res']                = res
            st.session_state['setup_time_val']     = setup_time_val
            st.session_state['priority_weight']    = priority_weight
            st.session_state['milp_time_limit']    = milp_time_limit
            st.session_state['waktu_selesai_dict'] = waktu_selesai_dict
            st.session_state['scores']             = scores
            st.session_state['scheds']             = scheds
            st.session_state['ends']               = ends
            st.session_state['pemenang']           = pemenang
            st.session_state['milp_feasible']      = milp_feasible
            st.session_state['milp_status']        = milp_status
            st.session_state['gap_pct_main']       = gap_pct_main
            st.session_state['bigm_info']          = bigm_info
            st.session_state['edd_score']          = edd_score
            st.session_state['sa_score']           = sa_score
            st.session_state['milp_score']         = milp_score

            progress_bar.progress(100, "✅ Selesai!")

        # ── Tampilkan hasil jika sudah ada di session state ────────────
        if 'jadwal_final' not in st.session_state:
            st.info("👆 Pilih order di tabel dan klik **JALANKAN OPTIMASI** untuk memulai.")
        else:
            # Ambil dari session state
            jadwal_final       = st.session_state['jadwal_final']
            waktu_selesai_dict = st.session_state['waktu_selesai_dict']
            job_ids            = st.session_state['job_ids']
            P                  = st.session_state['P']
            D                  = st.session_state['D']
            W                  = st.session_state['W']
            R                  = st.session_state['R']
            df_pool            = st.session_state['df_pool']
            start_date         = st.session_state['start_date']
            res                = st.session_state['res']
            setup_time_val     = st.session_state['setup_time_val']
            priority_weight    = st.session_state['priority_weight']
            milp_time_limit    = st.session_state['milp_time_limit']
            scores             = st.session_state['scores']
            scheds             = st.session_state['scheds']
            ends               = st.session_state['ends']
            pemenang           = st.session_state['pemenang']
            milp_feasible      = st.session_state['milp_feasible']
            milp_status        = st.session_state['milp_status']
            gap_pct_main       = st.session_state['gap_pct_main']
            bigm_info          = st.session_state['bigm_info']
            edd_score          = st.session_state['edd_score']
            sa_score           = st.session_state['sa_score']
            milp_score         = st.session_state['milp_score']
            existing_schedule_map = st.session_state['existing_schedule']

            # Post-processing
            sc = jalankan_sanity_check(jadwal_final, df_pool, P, start_date)

            laporan_order  = []
            jadwal_op_rows = []
            pesanan_telat  = 0

            for i in job_ids:
                target_nyata  = df_pool[df_pool['id pesanan'].astype(str) == i]['target_dt'].iloc[0]
                selesai_nyata = konversi_ke_jam_dinding(waktu_selesai_dict[i], start_date)
                selisih_mnt   = (selesai_nyata - target_nyata).total_seconds() / 60
                status_ord    = 'Telat' if selisih_mnt > 0 else 'Tepat Waktu'
                if selisih_mnt > 0:
                    pesanan_telat += 1

                laporan_order.append({
                    'ID Pesanan'      : i,
                    'Prioritas'       : "⭐ Ya" if W[i] > 1 else "Tidak",
                    'Target Selesai'  : target_nyata.strftime('%d-%b-%y %H:%M'),
                    'Estimasi Selesai': selesai_nyata.strftime('%d-%b-%y %H:%M'),
                    'Status'          : status_ord,
                    'Telat (Hari)'    : math.ceil(max(0, selisih_mnt) / MENIT_PER_HARI),
                })

            for t in jadwal_final:
                qty_row = df_pool[df_pool['id pesanan'].astype(str) == t['job']]['qty'].iloc[0]
                jadwal_op_rows.append({
                    'Stasiun Kerja': t['m'],
                    'ID Pesanan'   : t['job'],
                    'Qty'          : qty_row,
                    'Mulai'        : konversi_ke_jam_dinding(t['start'], start_date).strftime('%d-%b-%y %H:%M'),
                    'Selesai'      : konversi_ke_jam_dinding(t['start'] + t['dur'], start_date).strftime('%d-%b-%y %H:%M'),
                })

            df_gantt   = build_gantt_df(jadwal_final, df_pool, start_date)
            df_laporan = pd.DataFrame(laporan_order).sort_values(
                by=['Status', 'Estimasi Selesai'], ascending=[False, True]
            )
            df_op = pd.DataFrame(jadwal_op_rows)

            # ============================================================
            # 14. DASHBOARD — RINGKASAN METRIK
            # ============================================================
            st.divider()
            m1, m2, m3, m4, m5, m6 = st.columns(6)
            m1.metric("📦 Total Order",     len(job_ids))
            m2.metric("✅ Tepat Waktu",     len(job_ids) - pesanan_telat)
            m3.metric("🚨 Terlambat",       pesanan_telat, delta_color="inverse")
            m4.metric("🏆 Pemenang",        pemenang)
            m5.metric("📉 Skor Penalti",    f"{scores[pemenang]:,.1f}")
            # [FIX-2] Optimality gap
            gap_str = f"{gap_pct_main:.2f}%" if gap_pct_main is not None else "N/A"
            m6.metric("🎯 MILP Gap",        gap_str,
                      help="Gap = 0% berarti solusi MILP terbukti optimal secara matematis.")

            # Perbandingan tiga metode — [FIX-3] EDD ditambahkan
            with st.container(border=True):
                st.markdown("**📊 Perbandingan Tiga Metode**")
                cc1, cc2, cc3 = st.columns(3)
                method_colors = {
                    'EDD'               : ("#FEF3C7", "#92400E", "📋"),
                    'Simulated Annealing': ("#DBEAFE", "#1E40AF", "🔥"),
                    'MILP'              : ("#DCFCE7", "#166534", "⚙️"),
                }
                for col, method in zip([cc1, cc2, cc3], ['EDD', 'Simulated Annealing', 'MILP']):
                    bg, fg, icon = method_colors[method]
                    score_val = scores[method]
                    score_str = f"{score_val:,.2f}" if score_val < float('inf') else "Tidak feasible"
                    is_winner = (method == pemenang)
                    border    = "3px solid #166534" if is_winner else "1px solid #E5E7EB"
                    col.markdown(
                        f'<div style="background:{bg};padding:12px;border-radius:10px;border:{border}">'
                        f'{icon} <b>{"🏆 " if is_winner else ""}{method}</b><br>'
                        f'Skor Penalti: <b>{score_str}</b>'
                        f'{"<br><small style=color:" + fg + ">← Terpilih</small>" if is_winner else ""}'
                        f'</div>',
                        unsafe_allow_html=True,
                    )

            # BigM info + gap caption
            if bigm_info:
                bigm_aktif = {k: v for k, v in bigm_info.items() if v > 1.0}
                bigm_str   = " · ".join(
                    f"{k.split('. ', 1)[-1]}={v:.0f}" for k, v in bigm_aktif.items()
                )
                gap_info = f"MILP Gap: {gap_pct_main:.2f}%" if gap_pct_main is not None else f"MILP: {milp_status}"
                st.caption(
                    f"🔧 BigM per-mesin: {bigm_str} · {gap_info} · "
                    f"SA: 8.000 iter, T₀=500, α=0.997 · W(prioritas)={priority_weight:,}"
                )

            # ============================================================
            # 15. TAB DASHBOARD
            # ============================================================
            tab1, tab2, tab3, tab4, tab5, tab6 = st.tabs([
                "📊 Gantt — Pemenang",
                "📊 Gantt — Pembanding",
                "📑 Laporan Manajemen",
                "👨‍🔧 Lembar Kerja Operator",
                "🔎 Audit & Sanity Check",
                "🆕 Estimasi Order Baru",
            ])

            # ── TAB 1: Gantt Pemenang ─────────────────────────────────
            with tab1:
                st.markdown(f"**Jadwal Akhir Produksi** — dihasilkan oleh: *{pemenang}*")
                if not df_gantt.empty:
                    fig1 = px.timeline(
                        df_gantt,
                        x_start="Mulai", x_end="Selesai",
                        y="Stasiun Kerja", color="ID Pesanan",
                        hover_data=["Durasi (Menit)", "Qty"],
                        title=f"Gantt Chart: {pemenang} (Skor: {scores[pemenang]:,.2f})",
                    )
                    fig1.update_yaxes(categoryorder="array", categoryarray=STATIONS[::-1])
                    fig1.update_layout(height=500, plot_bgcolor='rgba(0,0,0,0)',
                                       paper_bgcolor='rgba(0,0,0,0)')
                    st.plotly_chart(fig1, use_container_width=True)
                else:
                    st.warning("Tidak ada data jadwal untuk ditampilkan.")

            # ── TAB 2: Gantt Pembanding ───────────────────────────────
            with tab2:
                st.markdown("**Perbandingan semua metode secara visual**")
                sub1, sub2 = st.tabs(["EDD vs Pemenang", "SA vs Pemenang"])

                for sub_tab, compare_method in zip([sub1, sub2], ['EDD', 'Simulated Annealing']):
                    with sub_tab:
                        cmp_sched = scheds[compare_method]
                        if cmp_sched:
                            df_cmp = build_gantt_df(cmp_sched, df_pool, start_date)
                            fig_cmp = px.timeline(
                                df_cmp,
                                x_start="Mulai", x_end="Selesai",
                                y="Stasiun Kerja", color="ID Pesanan",
                                hover_data=["Durasi (Menit)", "Qty"],
                                title=f"{compare_method} (Skor: {scores[compare_method]:,.2f})",
                            )
                            fig_cmp.update_yaxes(categoryorder="array", categoryarray=STATIONS[::-1])
                            fig_cmp.update_layout(height=500, plot_bgcolor='rgba(0,0,0,0)',
                                                   paper_bgcolor='rgba(0,0,0,0)')
                            st.plotly_chart(fig_cmp, use_container_width=True)

                with st.expander("📋 Perbandingan Skor per Order (tabel)"):
                    rows_cmp = []
                    for i in job_ids:
                        tgt   = df_pool[df_pool['id pesanan'].astype(str) == i]['target_dt'].iloc[0]
                        def _fmt(end_d, mthd):
                            e = end_d.get(mthd, {}).get(i)
                            if e is None:
                                return 'N/A'
                            return konversi_ke_jam_dinding(e, start_date).strftime('%d-%b-%y %H:%M')
                        rows_cmp.append({
                            'ID Pesanan': i,
                            'EDD'       : _fmt(ends, 'EDD'),
                            'SA'        : _fmt(ends, 'Simulated Annealing'),
                            'MILP'      : _fmt(ends, 'MILP') if milp_feasible else 'N/A',
                            'Target'    : tgt.strftime('%d-%b-%y %H:%M'),
                        })
                    st.dataframe(pd.DataFrame(rows_cmp), hide_index=True, use_container_width=True)

            # ── TAB 3: Laporan Manajemen ──────────────────────────────
            with tab3:
                st.markdown("**Status Penyelesaian Order per Tenggat Waktu**")
                def color_status(val):
                    return ('background-color:#F87171;color:white' if val == 'Telat'
                            else 'background-color:#34D399;color:white')
                st.dataframe(
                    df_laporan.style.map(color_status, subset=['Status']),
                    use_container_width=True, height=420,
                )

            # ── TAB 4: Lembar Kerja Operator ──────────────────────────
            with tab4:
                st.markdown("**Instruksi Kerja (Work Order) per Stasiun Kerja**")
                for stasiun in STATIONS:
                    df_st = df_op[df_op['Stasiun Kerja'] == stasiun]
                    if df_st.empty:
                        continue
                    with st.expander(f"📁 {stasiun} — {len(df_st)} order"):
                        st.dataframe(
                            df_st.drop(columns=['Stasiun Kerja']),
                            hide_index=True, use_container_width=True,
                        )

            # ── TAB 5: Audit & Sanity Check ───────────────────────────
            with tab5:
                st.markdown("### 🔎 Audit Otomatis — Verifikasi Logika Jadwal")

                if sc['err_overlap'] or sc['err_presedens'] or not sc['tabel_minggu'].empty:
                    st.error("🚨 **Sanity Check GAGAL** — ditemukan pelanggaran.")
                else:
                    st.success("✅ **Sanity Check PASSED** — Jadwal valid, tidak ada pelanggaran.")

                with st.expander("📄 Log Teks Lengkap", expanded=False):
                    st.code(sc['log_text'], language="text")

                st.divider()

                # Overlap
                st.markdown("#### [1] Pemeriksaan Overlap Mesin")
                if sc['err_overlap']:
                    st.error("❌ Ditemukan overlap!")
                else:
                    st.success("✔️ Tidak ada dua order yang menempati mesin yang sama secara bersamaan.")

                st.divider()

                # Presedensi OPC
                st.markdown(f"#### [2] Verifikasi Presedensi — Order: `{sc['sample_job_id']}`")
                sr   = sc['sample_row']
                rute = sc['sample_rute']
                if sr:
                    col_spec1, col_spec2 = st.columns(2)
                    with col_spec1:
                        st.markdown("**Spesifikasi Order:**")
                        spec_data = {
                            'Atribut': ['ID Pesanan', 'Jenis Produk', 'Qty', 'Due Date',
                                        'Furing', 'Sablon', 'DTF', 'Bordir', 'Pasang Kancing'],
                            'Nilai'  : [
                                str(sr.get('id pesanan', '-')),
                                str(sr.get('jenis produk', '-')).capitalize(),
                                str(int(sr.get('qty', 0))),
                                pd.Timestamp(sr.get('due date (tanggal)', '')).strftime('%d-%b-%Y')
                                    if sr.get('due date (tanggal)') else '-',
                                '✅ Ya' if sr.get('furing', 0) == 1 else '❌ Tidak',
                                '✅ Ya' if sr.get('sablon', 0) == 1 else '❌ Tidak',
                                '✅ Ya' if sr.get('dtf',    0) == 1 else '❌ Tidak',
                                '✅ Ya' if sr.get('bordir', 0) == 1 else '❌ Tidak',
                                '✅ Ya' if sr.get('pasang kancing', 0) == 1 else '❌ Tidak',
                            ],
                        }
                        st.dataframe(pd.DataFrame(spec_data), hide_index=True, use_container_width=True)

                    with col_spec2:
                        st.markdown("**Routing Aktif (OPC):**")
                        p_sample = P.get(sc['sample_job_id'], {})
                        opc_rows = [
                            {'Urutan': idx + 1, 'Stasiun': m,
                             'Pᵢₘ (mnt)': round(p_sample.get(m, 0), 2)}
                            for idx, m in enumerate(rute)
                        ]
                        st.dataframe(pd.DataFrame(opc_rows), hide_index=True, use_container_width=True)

                if rute:
                    p_sample = P.get(sc['sample_job_id'], {})
                    opc_fig  = go.Figure()
                    n        = len(rute)
                    for xi, m in enumerate(rute):
                        d       = round(p_sample.get(m, 0), 2)
                        short_m = m.split('. ', 1)[-1].replace('_', ' ')
                        opc_fig.add_trace(go.Scatter(
                            x=[xi], y=[0], mode='markers+text',
                            marker=dict(size=36, color='#1E3A8A', symbol='square'),
                            text=[f"<b>{xi+1}</b>"],
                            textposition='middle center',
                            textfont=dict(color='white', size=13),
                            hovertemplate=f"<b>{m}</b><br>Durasi: {d:.1f} mnt<extra></extra>",
                            showlegend=False,
                        ))
                        opc_fig.add_annotation(
                            x=xi, y=-0.18,
                            text=f"<b>{short_m}</b><br>{d:.1f} mnt",
                            showarrow=False,
                            font=dict(size=10, color='#1E3A8A'),
                            align='center',
                        )
                        if xi < n - 1:
                            opc_fig.add_annotation(
                                ax=xi + 0.08, ay=0, axref='x', ayref='y',
                                x=xi + 0.92, y=0, xref='x', yref='y',
                                showarrow=True, arrowhead=2, arrowsize=1.5,
                                arrowwidth=2, arrowcolor='#64748B',
                            )
                    opc_fig.update_layout(
                        height=200, margin=dict(l=20, r=20, t=20, b=80),
                        xaxis=dict(visible=False, range=[-0.6, n - 0.4]),
                        yaxis=dict(visible=False, range=[-0.5, 0.5]),
                        plot_bgcolor='rgba(0,0,0,0)', paper_bgcolor='rgba(0,0,0,0)',
                    )
                    st.plotly_chart(opc_fig, use_container_width=True)

                st.divider()

                # Hari Minggu
                st.markdown("#### [3] Verifikasi Hari Libur (Minggu)")
                if sc['tabel_minggu'].empty:
                    st.success("✔️ Tidak ada jadwal yang jatuh di Hari Minggu.")
                else:
                    st.error(f"❌ {len(sc['tabel_minggu'])} slot dijadwalkan di Hari Minggu!")
                    st.dataframe(sc['tabel_minggu'], hide_index=True, use_container_width=True)

                st.divider()

                # [FIX-5] Tabel Pᵢₘ (waktu proses per order per stasiun)
                st.markdown("#### [4] Tabel Waktu Proses Pᵢₘ per Order per Stasiun")
                st.caption(
                    "Pᵢₘ = total menit efektif pesanan i di stasiun m (sudah memperhitungkan "
                    "parallelisme kapasitas). Stasiun dengan Pᵢₘ = 0 tidak masuk routing aktif."
                )
                with st.expander("🔢 Lihat Tabel Pᵢₘ Lengkap"):
                    rows_p = []
                    for i in job_ids:
                        for m in STATIONS:
                            if P[i][m] > 0:
                                rows_p.append({
                                    'ID Pesanan'   : i,
                                    'Stasiun'      : m,
                                    'Pᵢₘ (menit)' : round(P[i][m], 2),
                                })
                    st.dataframe(pd.DataFrame(rows_p), hide_index=True, use_container_width=True)

                st.divider()

                # [FIX-2] Laporan optimality gap
                st.markdown("#### [5] Laporan Optimality Gap MILP")
                if gap_pct_main is not None:
                    if gap_pct_main < 0.01:
                        st.success(
                            f"✅ **Gap = {gap_pct_main:.4f}%** — Solusi MILP terbukti optimal "
                            f"secara matematis (atau sangat mendekati optimal)."
                        )
                    else:
                        st.warning(
                            f"⚠️ **Gap = {gap_pct_main:.2f}%** — Solusi MILP adalah near-optimal "
                            f"dalam batas waktu {milp_time_limit} detik. Tambah batas waktu untuk "
                            f"gap lebih kecil."
                        )
                elif not milp_feasible:
                    st.info(f"ℹ️ MILP tidak menghasilkan solusi feasible (status: {milp_status}). "
                            f"Jadwal menggunakan {pemenang}.")
                else:
                    st.info("ℹ️ Data gap tidak tersedia dari solver.")

                # BigM transparency
                if bigm_info:
                    st.markdown("#### [6] Nilai BigM per Stasiun")
                    st.caption(
                        "BigMₘ = Σᵢ Pᵢₘ (total durasi semua order di stasiun m). "
                        "Ini adalah batas atas ketat dari selisih start time manapun di stasiun tersebut."
                    )
                    bigm_df = pd.DataFrame(
                        [{'Stasiun': k, 'BigMₘ (menit)': v}
                         for k, v in bigm_info.items() if v > 1.0]
                    )
                    st.dataframe(bigm_df, hide_index=True, use_container_width=True)

            # ── TAB 6: ESTIMASI ORDER BARU ────────────────────────────
            with tab6:
                st.markdown("### 🆕 Estimasi Due Date Order Baru")
                st.markdown(
                    '<div class="info-box">'
                    '💡 Fitur ini memperkirakan <b>kapan tercepat order baru bisa diselesaikan</b> '
                    'tanpa membuat order yang sudah ada menjadi terlambat. '
                    'Order yang di-<b>Lock</b> posisinya dikunci permanen — '
                    'order baru tidak akan pernah menggeser mereka.'
                    '</div>',
                    unsafe_allow_html=True,
                )

                st.divider()

                # ── LANGKAH 1: Pilih order mana yang terkunci ──────────
                st.markdown("#### Langkah 1 — Tentukan Order yang Terkunci (Locked)")
                st.caption(
                    "Default: tidak ada yang terkunci. Centang **Lock** pada order yang "
                    "sedang dikerjakan atau sudah dikonfirmasi ke pelanggan sehingga "
                    "posisi & urutannya tidak boleh berubah sama sekali."
                )

                lock_data = []
                for i in job_ids:
                    match = df_pool[df_pool['id pesanan'].astype(str) == i]
                    if match.empty:
                        continue
                    row_d   = match.iloc[0]
                    tgt     = row_d['target_dt']
                    sel     = konversi_ke_jam_dinding(waktu_selesai_dict[i], start_date)
                    status  = '🟢 Tepat Waktu' if sel <= tgt else '🔴 Terlambat'
                    lock_data.append({
                        'Lock'              : False,
                        'ID Pesanan'        : i,
                        'Jenis'             : str(row_d['jenis produk']).capitalize(),
                        'Qty'               : int(row_d['qty']),
                        'Due Date'          : tgt.strftime('%d-%b-%y'),
                        'Est. Selesai'      : sel.strftime('%d-%b-%y %H:%M'),
                        'Status'            : status,
                    })

                lock_df_input = pd.DataFrame(lock_data)
                lock_edited   = st.data_editor(
                    lock_df_input,
                    column_config={
                        'Lock': st.column_config.CheckboxColumn(
                            "🔒 Lock",
                            help="Centang untuk mengunci posisi order ini. "
                                 "Order terkunci tidak akan bergeser sama sekali.",
                            default=False,
                        )
                    },
                    hide_index=True,
                    use_container_width=True,
                )

                locked_ids = set(
                    lock_edited[lock_edited['Lock'] == True]['ID Pesanan'].tolist()
                )
                n_locked = len(locked_ids)
                if n_locked > 0:
                    st.info(
                        f"🔒 **{n_locked} order dikunci:** "
                        f"`{', '.join(str(x) for x in locked_ids)}`"
                    )
                else:
                    st.caption("ℹ️ Tidak ada order yang dikunci — semua order boleh di-reschedule.")

                st.divider()

                # ── LANGKAH 2: Input order baru ────────────────────────
                st.markdown("#### Langkah 2 — Input Order Baru")
                st.caption(
                    "Masukkan satu atau lebih order baru. "
                    "Klik **+ Tambah Order** untuk menambah baris."
                )

                # Template default untuk order baru
                if 'new_orders_df' not in st.session_state:
                    st.session_state['new_orders_df'] = pd.DataFrame([{
                        'id pesanan'        : 'NEW-001',
                        'jenis produk'      : 'kaos',
                        'qty'               : 100,
                        'due date (tanggal)': (start_date + timedelta(days=14)).strftime('%d/%m/%Y'),
                        'furing'            : 0,
                        'sablon'            : 0,
                        'dtf'               : 0,
                        'bordir'            : 0,
                        'pasang kancing'    : 0,
                        'Priority'          : False,
                    }])

                new_orders_edited = st.data_editor(
                    st.session_state['new_orders_df'],
                    column_config={
                        'jenis produk': st.column_config.SelectboxColumn(
                            "Jenis Produk",
                            options=['kaos', 'polo', 'kemeja', 'jaket'],
                            required=True,
                        ),
                        'qty'         : st.column_config.NumberColumn("Qty", min_value=1),
                        'furing'      : st.column_config.NumberColumn("Furing (0/1)", min_value=0, max_value=1),
                        'sablon'      : st.column_config.NumberColumn("Sablon (0/1)", min_value=0, max_value=1),
                        'dtf'         : st.column_config.NumberColumn("DTF (0/1)", min_value=0, max_value=1),
                        'bordir'      : st.column_config.NumberColumn("Bordir (0/1)", min_value=0, max_value=1),
                        'pasang kancing': st.column_config.NumberColumn("Pasang Kancing (0/1)", min_value=0, max_value=1),
                        'Priority'    : st.column_config.CheckboxColumn("Priority ⭐"),
                    },
                    num_rows="dynamic",
                    hide_index=True,
                    use_container_width=True,
                )
                st.session_state['new_orders_df'] = new_orders_edited

                est_button = st.button(
                    "🔍 ESTIMASI JADWAL ORDER BARU",
                    type="primary",
                    use_container_width=True,
                )

                st.divider()

                # ── LANGKAH 3: Jalankan estimasi ───────────────────────
                if est_button:
                    if new_orders_edited.empty:
                        st.warning("⚠️ Masukkan minimal 1 order baru.")
                        st.stop()

                    # Validasi & parse order baru
                    try:
                        new_orders_raw = []
                        for _, nr in new_orders_edited.iterrows():
                            nr_dict = nr.to_dict()
                            nr_dict['due date (tanggal)'] = pd.to_datetime(
                                nr_dict['due date (tanggal)'], dayfirst=True, errors='coerce'
                            )
                            if pd.isna(nr_dict['due date (tanggal)']):
                                st.error(f"❌ Due date tidak valid untuk order `{nr_dict['id pesanan']}`.")
                                st.stop()
                            nr_dict['qty']    = float(nr_dict['qty'])
                            nr_dict['furing'] = int(nr_dict.get('furing', 0))
                            for bc in ['sablon', 'dtf', 'bordir', 'pasang kancing']:
                                nr_dict[bc] = int(nr_dict.get(bc, 0))
                            new_orders_raw.append(nr_dict)
                    except Exception as e:
                        st.error(f"❌ Error parsing order baru: {e}")
                        st.stop()

                    # Cek duplikasi ID
                    new_ids_input = [str(nr['id pesanan']) for nr in new_orders_raw]
                    duplikat = [x for x in new_ids_input if x in job_ids]
                    if duplikat:
                        st.error(
                            f"❌ ID pesanan berikut sudah ada di jadwal existing: `{duplikat}`. "
                            f"Gunakan ID yang berbeda."
                        )
                        st.stop()

                    with st.spinner(
                        f"🔄 Menjalankan joint re-optimization untuk "
                        f"{len(new_orders_raw)} order baru + "
                        f"{len(job_ids) - n_locked} order tidak terkunci…"
                    ):
                        est_result = estimasi_order_baru(
                            new_jobs_data       = new_orders_raw,
                            existing_job_ids    = job_ids,
                            locked_job_ids      = locked_ids,
                            existing_schedule   = existing_schedule_map,
                            P_dict_existing     = P,
                            D_dict_existing     = D,
                            W_dict_existing     = W,
                            R_dict_existing     = R,
                            resources           = res,
                            setup_time          = setup_time_val,
                            start_date          = start_date,
                            priority_weight     = priority_weight,
                            milp_time_limit     = milp_time_limit,
                        )

                    # ── Tampilkan hasil estimasi ─────────────────────
                    st.markdown("---")
                    st.markdown("#### 📊 Hasil Estimasi")
                    st.caption(f"Metode: {est_result['method']} · Skor penalti total: {est_result['score']:,.2f}")

                    # Metrik ringkasan untuk order baru
                    new_job_ids = est_result['new_job_ids']
                    end_times   = est_result['end_times']

                    summary_rows = []
                    for nj_id in new_job_ids:
                        comp_menit = end_times.get(nj_id, 0)
                        comp_dt    = konversi_ke_jam_dinding(comp_menit, start_date)
                        due_menit  = est_result['D_new'].get(nj_id, 0)
                        due_dt     = konversi_ke_jam_dinding(due_menit, start_date) if due_menit > 0 else None

                        # Hitung hari kerja sampai selesai
                        days_needed = math.ceil(comp_menit / MENIT_PER_HARI)
                        is_on_time  = (due_dt is None) or (comp_dt <= due_dt)

                        summary_rows.append({
                            'ID Pesanan'          : nj_id,
                            'Est. Selesai Tercepat': comp_dt.strftime('%d-%b-%Y %H:%M'),
                            'Due Date Diminta'     : due_dt.strftime('%d-%b-%Y') if due_dt else 'N/A',
                            'Status'               : '✅ Bisa Tepat Waktu' if is_on_time else '⚠️ Perlu Negosiasi',
                            'Rekomendasi Due Date' : comp_dt.strftime('%d-%b-%Y'),
                        })

                    df_summary = pd.DataFrame(summary_rows)
                    st.dataframe(df_summary, hide_index=True, use_container_width=True)

                    # Cek apakah order lama yang terkunci masih tepat waktu
                    st.markdown("#### 🔒 Verifikasi Order Terkunci")
                    if locked_ids:
                        lock_check_rows = []
                        semua_aman = True
                        for lj in locked_ids:
                            comp_menit_lj = end_times.get(lj, 0)
                            comp_dt_lj    = konversi_ke_jam_dinding(comp_menit_lj, start_date)
                            due_menit_lj  = D.get(lj, 0)
                            due_dt_lj     = konversi_ke_jam_dinding(due_menit_lj, start_date)
                            status_lj     = '✅ Aman' if comp_dt_lj <= due_dt_lj else '🚨 TERLAMBAT!'
                            if comp_dt_lj > due_dt_lj:
                                semua_aman = False
                            lock_check_rows.append({
                                'ID Pesanan'     : lj,
                                'Est. Selesai'   : comp_dt_lj.strftime('%d-%b-%y %H:%M'),
                                'Due Date'       : due_dt_lj.strftime('%d-%b-%y %H:%M'),
                                'Status'         : status_lj,
                            })
                        lock_check_df = pd.DataFrame(lock_check_rows)
                        if semua_aman:
                            st.success(
                                "✅ Semua order terkunci tetap tepat waktu — "
                                "penambahan order baru tidak mengganggu komitmen yang sudah ada."
                            )
                        else:
                            st.error(
                                "🚨 Ditemukan order terkunci yang terlambat! "
                                "Hal ini tidak seharusnya terjadi — cek feasibilitas kapasitas."
                            )
                        st.dataframe(lock_check_df, hide_index=True, use_container_width=True)
                    else:
                        st.info("ℹ️ Tidak ada order terkunci — semua order di-reschedule ulang bersama.")

                    # Gantt chart jadwal gabungan (existing + new)
                    st.markdown("#### 📅 Gantt Chart Jadwal Gabungan")
                    # Gabungkan df_pool + new orders untuk build_gantt_df
                    new_df_for_gantt = pd.DataFrame(new_orders_raw)
                    new_df_for_gantt['id pesanan'] = new_df_for_gantt['id pesanan'].astype(str)
                    df_pool_combined = pd.concat(
                        [df_pool[['id pesanan', 'qty']], new_df_for_gantt[['id pesanan', 'qty']]],
                        ignore_index=True,
                    )
                    df_gantt_combined = build_gantt_df(est_result['sched'], df_pool_combined, start_date)

                    if not df_gantt_combined.empty:
                        # Beri warna berbeda untuk order baru
                        df_gantt_combined['Tipe'] = df_gantt_combined['ID Pesanan'].apply(
                            lambda x: '🆕 Order Baru' if x in new_job_ids else '📦 Order Lama'
                        )
                        fig_est = px.timeline(
                            df_gantt_combined,
                            x_start="Mulai", x_end="Selesai",
                            y="Stasiun Kerja", color="ID Pesanan",
                            hover_data=["Durasi (Menit)", "Qty", "Tipe"],
                            title="Jadwal Gabungan (Order Lama + Order Baru)",
                            pattern_shape="Tipe",
                            pattern_shape_map={
                                '🆕 Order Baru': '/',
                                '📦 Order Lama': '',
                            },
                        )
                        fig_est.update_yaxes(categoryorder="array", categoryarray=STATIONS[::-1])
                        fig_est.update_layout(
                            height=520,
                            plot_bgcolor='rgba(0,0,0,0)',
                            paper_bgcolor='rgba(0,0,0,0)',
                        )
                        st.plotly_chart(fig_est, use_container_width=True)
                        st.caption(
                            "Order baru ditampilkan dengan pola garis miring (//). "
                            "Order lama ditampilkan solid."
                        )

                    # Export jadwal gabungan
                    buf_est = io.BytesIO()
                    with pd.ExcelWriter(buf_est, engine='openpyxl') as writer:
                        df_summary.to_excel(writer, sheet_name='Estimasi Order Baru', index=False)
                        df_gantt_combined.to_excel(writer, sheet_name='Jadwal Gabungan', index=False)
                        if lock_check_rows if locked_ids else False:
                            pd.DataFrame(lock_check_rows).to_excel(
                                writer, sheet_name='Verifikasi Order Terkunci', index=False
                            )

                    st.download_button(
                        "⬇️ Download Estimasi + Jadwal Gabungan .xlsx",
                        data=buf_est.getvalue(),
                        file_name=f"Estimasi_Order_Baru_{datetime.now().strftime('%d%b%Y_%H%M')}.xlsx",
                        mime="application/vnd.ms-excel",
                        type="secondary",
                    )

            # ============================================================
            # 16. DOWNLOAD EXCEL JADWAL UTAMA
            # ============================================================
            st.divider()
            st.subheader("📥 Unduh Rekap Excel — Jadwal Utama")

            buf = io.BytesIO()
            with pd.ExcelWriter(buf, engine='openpyxl') as writer:
                df_laporan.to_excel(writer, sheet_name='Laporan Manajemen', index=False)
                df_op.to_excel(writer,      sheet_name='Jadwal per Stasiun', index=False)
                # Tambahkan sheet perbandingan tiga metode
                rows_cmp_export = []
                for i in job_ids:
                    tgt = df_pool[df_pool['id pesanan'].astype(str) == i]['target_dt'].iloc[0]
                    def _fmt_e(end_d, mthd):
                        e = end_d.get(mthd, {}).get(i)
                        if e is None:
                            return 'N/A'
                        return konversi_ke_jam_dinding(e, start_date).strftime('%d-%b-%y %H:%M')
                    rows_cmp_export.append({
                        'ID Pesanan': i,
                        'EDD'       : _fmt_e(ends, 'EDD'),
                        'SA'        : _fmt_e(ends, 'Simulated Annealing'),
                        'MILP'      : _fmt_e(ends, 'MILP') if milp_feasible else 'N/A',
                        'Target'    : tgt.strftime('%d-%b-%y %H:%M'),
                        'Metode Terpilih': pemenang,
                    })
                pd.DataFrame(rows_cmp_export).to_excel(
                    writer, sheet_name='Perbandingan 3 Metode', index=False
                )

            st.download_button(
                "⬇️ Download Laporan .xlsx",
                data=buf.getvalue(),
                file_name=f"Jadwal_Pabrik_{datetime.now().strftime('%d%b%Y_%H%M')}.xlsx",
                mime="application/vnd.ms-excel",
                type="secondary",
            )

    except Exception as e:
        st.error(f"🚨 Terjadi kesalahan: {e}")
        import traceback
        st.code(traceback.format_exc(), language="text")